services:
  backend:
    build: backend
    ports:
      - "5000:5000" 
    networks:
      - mern
    environment:
      MONGO_URI: mongodb+srv://prakashporiya:prakash6985@cluster0.h7c3t.mongodb.net/ 
    depends_on:
      - mongo

  frontend:
    build: frontend
    ports:
      - "5173:80"  
    networks:
      - mern
    environment:
      REACT_APP_API_URL: http://backend:5000 

  mongo:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern
    volumes:
      - mongo-data:/data/db  

networks:
  mern:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally